import { Link } from "react-router-dom";
import { ArrowRight, CheckCircle2, FileText, HeartHandshake, MessageCircleHeart, Mic, ShieldCheck, Sparkles } from "lucide-react";
import BrandMark from "../../components/brand/BrandMark";

const features = [
  { icon: MessageCircleHeart, title: "Start with your own words", text: "A guided, adaptive conversation helps you share what matters without medical jargon." },
  { icon: Mic, title: "Speak when typing is hard", text: "Voice input is available alongside text, so you are always in control of what is shared." },
  { icon: FileText, title: "Keep the story connected", text: "Your completed health conversations appear in one personal timeline." },
];

export default function Home() {
  return <div className="landing-page">
    <header className="landing-header"><Link to="/" className="focus-ring rounded-xl"><BrandMark /></Link><nav><a href="#how-it-works">How it works</a><a href="#privacy">Privacy</a></nav><div className="header-actions"><Link to="/auth?mode=login" className="button-quiet">Sign in</Link><Link to="/auth?mode=register" className="button-primary button-small">Create account <ArrowRight size={16}/></Link></div></header>
    <main>
      <section className="hero-section"><div className="hero-copy"><span className="eyebrow"><Sparkles size={14}/>PERSONAL HEALTH INTAKE</span><h1>Your health story, <em>made clear</em>.</h1><p>Vaidyam gives you a calm space to explain how you feel, then organizes that information so the next conversation with a clinician can start with understanding.</p><div className="hero-actions"><Link className="button-primary" to="/auth?mode=register">Get started <ArrowRight size={18}/></Link><Link className="button-secondary" to="/auth?mode=login">I already have an account</Link></div><div className="hero-footnote"><ShieldCheck size={17}/><span>Consent-first and designed to keep you in control.</span></div></div>
        <div className="hero-art" aria-hidden="true"><div className="hero-orb hero-orb-one"/><div className="hero-orb hero-orb-two"/><div className="story-card story-card-main"><div className="story-card-top"><span className="story-avatar"><HeartHandshake size={22}/></span><span><b>Your health check-in</b><small>Private, patient-reported</small></span><CheckCircle2 size={21}/></div><div className="story-line short"/><div className="story-line"/><div className="story-prompt"><MessageCircleHeart size={19}/><span>Tell us what brought you here today.</span></div><div className="story-choice">I have a symptom I want to discuss</div></div><div className="story-card story-card-note"><span>Today</span><b>Health information, structured with care.</b></div></div>
      </section>
      <section id="how-it-works" className="how-section"><div><span className="eyebrow">SIMPLE BY DESIGN</span><h2>Less form-filling. More being heard.</h2></div><div className="feature-grid">{features.map(({ icon: Icon, title, text }, index) => <article key={title} className="feature-card"><span className="feature-number">0{index + 1}</span><span className="feature-icon"><Icon size={23}/></span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
      <section id="privacy" className="privacy-section"><div className="privacy-icon"><ShieldCheck size={27}/></div><div><span className="eyebrow eyebrow-light">YOUR INFORMATION, YOUR SAY</span><h2>Health information deserves a careful home.</h2><p>Vaidyam distinguishes what you tell us from information generated by the system. It does not diagnose or replace a clinician’s advice.</p></div><Link className="button-light" to="/auth?mode=register">Start securely <ArrowRight size={17}/></Link></section>
    </main>
    <footer className="landing-footer"><BrandMark/><p>Vaidyam is a health-intake platform, not an emergency service. If you believe you are experiencing an emergency, seek immediate local medical care.</p><span>© {new Date().getFullYear()} Vaidyam</span></footer>
  </div>;
}
