import { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import { Link, useSearchParams } from "react-router-dom";
import { ArrowLeft, ArrowRight, ClipboardList, FileText, Info, MessageCircleHeart, ShieldCheck } from "lucide-react";
import { fetchConsultation } from "../../consultation/consultationsSlice";
import { fetchIntake, fetchIntakeAnswers, fetchIntakeForConsultation } from "../../intake/intakeSlice";
import { formatDate, titleCase } from "../utils/health";

const sections = ["CHIEF_COMPLAINT", "SYMPTOM_HISTORY", "SEVERITY", "ASSOCIATED_SYMPTOMS", "MEDICAL_HISTORY", "MEDICATIONS", "ALLERGIES", "LIFESTYLE", "CURRENT_COMPLAINT", "DIGESTION", "APPETITE", "SLEEP", "BOWEL_HABITS", "AYUSH_OBSERVATIONS"];
const answerText = (answer) => Array.isArray(answer) ? answer.join(", ") : typeof answer === "boolean" ? answer ? "Yes" : "No" : String(answer || "Not answered");

export default function HealthSummaryLive() {
  const dispatch = useDispatch(); const [params] = useSearchParams(); const consultationId = params.get("consultation"); const intakeId = params.get("intake"); const { active: consultation } = useSelector((state) => state.consultations); const { active: intake, answers, status, error } = useSelector((state) => state.intake);
  useEffect(() => { const load = async () => { try { if (consultationId) await dispatch(fetchConsultation(consultationId)).unwrap(); const savedIntake = intakeId ? await dispatch(fetchIntake(intakeId)).unwrap() : await dispatch(fetchIntakeForConsultation(consultationId)).unwrap(); await dispatch(fetchIntakeAnswers(savedIntake._id)).unwrap(); } catch { /* Redux stores the normalized request error. */ } }; if (consultationId || intakeId) load(); }, [consultationId, dispatch, intakeId]);
  if (!consultationId && !intakeId) return <section className="content-page narrow"><span className="eyebrow">HEALTH SUMMARY</span><h1>There is no saved conversation selected.</h1><p className="page-intro">Choose a consultation record from your conversation history to review its patient-reported answers.</p><Link className="button-primary" to="/patient/timeline">View conversation history</Link></section>;
  if (status === "loading" || !intake) return <div className="page-state"><span className="loading-dot"/>Preparing your saved health information…</div>;
  if (error) return <section className="content-page narrow"><span className="eyebrow">HEALTH SUMMARY</span><h1>We could not load this conversation.</h1><p className="page-intro">{error.message}</p><Link className="button-primary" to="/patient/timeline">View conversation history</Link></section>;
  if (intake.status === "IN_PROGRESS") return <section className="content-page narrow"><span className="eyebrow">CONVERSATION IN PROGRESS</span><h1>Your saved answers are ready to resume.</h1><p className="page-intro">This health intake is not complete yet. Continue from the last saved answer whenever you are ready.</p><Link className="button-primary" to={`/patient/intake?system=${intake.intakeType}&intake=${intake._id}`}>Resume intake <ArrowRight size={17}/></Link></section>;
  const grouped = answers.reduce((groups, item) => ({ ...groups, [item.section]: [...(groups[item.section] || []), item] }), {});
  return <section className="summary-page"><Link to="/patient/timeline" className="back-link"><ArrowLeft size={17}/>Back to conversation history</Link><div className="summary-heading"><div><span className="eyebrow">PATIENT-REPORTED CONVERSATION RECORD</span><h1>{consultation?.chiefComplaint || "Health conversation"}</h1><p>Started {formatDate(intake.startedAt)} · {intake.intakeType === "AYUSH" ? "AYUSH health intake" : "Modern health intake"}</p></div><span className="summary-status"><ShieldCheck size={17}/>Saved intake</span></div><div className="summary-disclaimer"><Info size={20}/><p><b>Important:</b> The details below are patient-reported responses saved during this intake. Vaidyam has not generated a clinical diagnosis or verified these as medical facts.</p></div><div className="summary-grid"><section className="summary-main"><article className="summary-concern"><span className="card-kicker">PRIMARY HEALTH CONCERN</span><h2>{consultation?.chiefComplaint || "Health conversation"}</h2><p>{answers.length ? `${answers.length} responses were recorded in this conversation.` : "No detailed responses were recorded."}</p></article>{sections.filter((section) => grouped[section]?.length).map((section) => <article key={section} className="summary-section"><h2>{titleCase(section)}</h2><dl>{grouped[section].map((item) => <div key={`${item.questionId}-${item.answeredAt}`}><dt>{item.question}</dt><dd>{answerText(item.answer)}</dd></div>)}</dl></article>)}</section><aside className="summary-side"><article><ClipboardList size={22}/><h2>Conversation record</h2><p>Responses are kept in the order you shared them, so you can review exactly what was saved.</p><span>{answers.length} saved responses</span></article><article><FileText size={22}/><h2>Documents</h2><p>Document upload and extraction are not available from the current backend yet.</p><Link to="/patient/documents" className="text-link">Check document availability</Link></article><article className="summary-safe"><MessageCircleHeart size={22}/><h2>For your next visit</h2><p>You may share this intake with a healthcare professional, who remains responsible for assessment and care decisions.</p></article></aside></div></section>;
}
