import { useEffect, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { Link, useNavigate, useSearchParams } from "react-router-dom";
import { ArrowRight, CalendarDays, CircleAlert, FileText, MessageCircleHeart, SlidersHorizontal } from "lucide-react";
import { fetchConsultations } from "../../consultation/consultationsSlice";
import { fetchIntakeForConsultation } from "../../intake/intakeSlice";
import { formatDate, titleCase } from "../utils/health";

export default function HealthTimelineLive() { const dispatch = useDispatch(); const navigate = useNavigate(); const [params] = useSearchParams(); const { items, status, error } = useSelector((state) => state.consultations); const [filter, setFilter] = useState("ALL"); const [resuming, setResuming] = useState(""); useEffect(() => { dispatch(fetchConsultations()); }, [dispatch]); const filtered = items.filter((item) => filter === "ALL" || item.healthcareSystem === filter); const resume = async (item) => { setResuming(item._id); try { const intake = await dispatch(fetchIntakeForConsultation(item._id)).unwrap(); navigate(`/patient/intake?system=${item.healthcareSystem}&intake=${intake._id}`); } finally { setResuming(""); } }; if (status === "loading" && !items.length) return <div className="page-state"><span className="loading-dot"/>Loading your health history…</div>; return <section className="content-page timeline-page"><span className="eyebrow">CONVERSATION HISTORY</span><h1>Your health conversations</h1><p className="page-intro">This activity list is derived from your persisted consultation records. It is not a separate backend-provided medical timeline.</p>{error && <p className="notice-error" role="alert"><CircleAlert size={18}/>{error}</p>}<div className="timeline-toolbar"><span><SlidersHorizontal size={17}/>Filter records</span><div>{[["ALL","All records"],["MODERN","Modern"],["AYUSH","AYUSH"]].map(([value, label]) => <button onClick={() => setFilter(value)} key={value} className={filter === value ? "filter-active" : ""}>{label}</button>)}</div></div>{filtered.length ? <div className="timeline">{filtered.map((item) => <TimelineItem key={item._id} item={item} focused={params.get("focus") === item._id} onResume={resume} resuming={resuming === item._id}/>)}</div> : <div className="empty-card"><span><CalendarDays size={26}/></span><h3>No health conversations yet</h3><p>Complete a health intake and it will appear here as a patient-reported consultation record.</p><Link className="button-primary button-small" to="/patient/healthcare">Start an intake <ArrowRight size={16}/></Link></div>}</section>; }
function TimelineItem({ item, focused, onResume, resuming }) { const completed = item.status === "COMPLETED"; return <article className={`timeline-item ${focused ? "timeline-item-focused" : ""}`}><div className="timeline-marker"><MessageCircleHeart size={17}/></div><div className="timeline-date"><span>{formatDate(item.completedAt || item.createdAt, { day: "numeric", month: "short" })}</span><small>{new Intl.DateTimeFormat("en-IN", { year: "numeric" }).format(new Date(item.completedAt || item.createdAt))}</small></div><div className="timeline-content"><span className={`status-chip status-${item.status.toLowerCase()}`}>{titleCase(item.status)}</span><h2>{item.chiefComplaint}</h2><p>{item.healthcareSystem === "AYUSH" ? "AYUSH health intake" : "Modern health intake"} · {completed ? "Completed" : "Conversation in progress"}</p>{completed ? <Link className="text-link" to={`/patient/summary?consultation=${item._id}`}>Review saved responses <ArrowRight size={16}/></Link> : <button disabled={resuming} onClick={() => onResume(item)} className="text-link">{resuming ? "Opening…" : "Resume intake"}<ArrowRight size={16}/></button>}{!completed && <span className="timeline-note"><FileText size={15}/>Your saved answers will be restored when you resume.</span>}</div></article>; }
