import { useCallback, useEffect, useRef, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { Link, useNavigate, useSearchParams } from "react-router-dom";
import { ArrowLeft, ArrowRight, CheckCircle2, CircleAlert, Mic, Pause, Send, Sparkles, Volume2, X } from "lucide-react";
import { createConsultation } from "../../consultation/consultationsSlice";
import { createIntake, fetchIntake, fetchIntakeAnswers, fetchIntakeQuestion, submitIntakeAnswer } from "../intakeSlice";
import { titleCase } from "../../patient/utils/health";

const emptyAnswer = (question) => question?.answerType === "MULTI_SELECT" ? [] : "";
const missingAnswer = (value) => value === "" || value === null || value === undefined || (Array.isArray(value) && value.length === 0);

export default function IntakeRedux() {
  const dispatch = useDispatch(); const [params] = useSearchParams(); const navigate = useNavigate(); const intakeId = params.get("intake"); const system = params.get("system") === "AYUSH" ? "AYUSH" : "MODERN"; const { active: intake, question, answers, status, error: intakeError } = useSelector((state) => state.intake);
  const [complaint, setComplaint] = useState(""); const [answer, setAnswer] = useState(""); const [view, setView] = useState(intakeId ? "loading" : "start"); const [formError, setFormError] = useState(""); const [voiceState, setVoiceState] = useState("idle"); const recognition = useRef(null);
  const load = useCallback(async (id) => { setView("loading"); setFormError(""); try { const savedIntake = await dispatch(fetchIntake(id)).unwrap(); await dispatch(fetchIntakeAnswers(id)).unwrap(); if (savedIntake.status === "COMPLETED") { setView("complete"); return; } const next = await dispatch(fetchIntakeQuestion(id)).unwrap(); setAnswer(emptyAnswer(next)); setView("conversation"); } catch (requestError) { if (requestError?.status === 409) setView("complete"); else { setFormError(requestError?.message || "We could not restore this intake."); setView("error"); } } }, [dispatch]);
  useEffect(() => { if (intakeId) load(intakeId); }, [intakeId, load]);
  useEffect(() => () => recognition.current?.stop?.(), []);
  const start = async (event) => { event.preventDefault(); if (complaint.trim().length < 3) { setFormError("Please describe your main concern in at least three characters."); return; } setFormError(""); try { const consultation = await dispatch(createConsultation({ healthcareSystem: system, chiefComplaint: complaint.trim() })).unwrap(); const created = await dispatch(createIntake({ consultationId: consultation._id })).unwrap(); navigate(`/patient/intake?system=${system}&intake=${created._id}`, { replace: true }); } catch (requestError) { setFormError(requestError?.message || requestError || "We could not start your health intake."); } };
  const submit = async () => { if (question?.required && missingAnswer(answer)) { setFormError("Please share an answer before continuing."); return; } setFormError(""); try { const saved = await dispatch(submitIntakeAnswer({ intakeId: intake._id, answer: question.answerType === "NUMBER" && answer !== "" ? Number(answer) : answer })).unwrap(); await dispatch(fetchIntakeAnswers(intake._id)).unwrap(); if (saved.status === "COMPLETED") { setView("complete"); return; } const next = await dispatch(fetchIntakeQuestion(intake._id)).unwrap(); setAnswer(emptyAnswer(next)); } catch (requestError) { if (requestError?.status === 409) setView("complete"); else setFormError(requestError?.message || "We could not save this answer."); } };
  const speak = () => { if (question && window.speechSynthesis) { window.speechSynthesis.cancel(); window.speechSynthesis.speak(new SpeechSynthesisUtterance(question.question)); } };
  const startVoice = () => { const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition; if (!SpeechRecognition) { setVoiceState("unsupported"); return; } const listener = new SpeechRecognition(); listener.lang = "en-IN"; listener.interimResults = true; listener.onstart = () => setVoiceState("listening"); listener.onresult = (event) => setAnswer(Array.from(event.results).map((result) => result[0].transcript).join("")); listener.onerror = (event) => setVoiceState(event.error === "not-allowed" ? "permission" : "error"); listener.onend = () => setVoiceState((current) => current === "listening" ? "ready" : current); recognition.current = listener; listener.start(); };
  const toggle = (option) => setAnswer((current) => current.includes(option) ? current.filter((item) => item !== option) : [...current, option]); const error = formError || intakeError?.message;
  if (view === "loading") return <div className="page-state"><span className="loading-dot"/>Restoring your health intake…</div>;
  if (view === "error") return <section className="content-page narrow"><span className="eyebrow">INTAKE UNAVAILABLE</span><h1>We could not open this health conversation.</h1><p className="page-intro">{error}</p><div className="button-row"><button onClick={() => intakeId ? load(intakeId) : navigate("/patient/healthcare")} className="button-primary">Try again</button><Link to="/patient/dashboard" className="button-secondary">Back to overview</Link></div></section>;
  if (view === "start") return <section className="intake-start-page"><Link to="/patient/healthcare" className="back-link"><ArrowLeft size={17}/>Choose a different intake</Link><div className="intake-start-grid"><div><span className="eyebrow">{system === "AYUSH" ? "AYUSH HEALTH INTAKE" : "MODERN HEALTH INTAKE"}</span><h1>Start with what matters most.</h1><p>You do not need to use clinical language. Tell us, in your own words, what you would like to discuss.</p><div className="intake-promise"><Sparkles size={20}/><span>The next questions are prepared from this starting point. You can pause after any answer.</span></div></div><form className="complaint-card" onSubmit={start}>{error && <p className="notice-error" role="alert"><CircleAlert size={18}/>{error}</p>}<label htmlFor="chief-complaint">What brought you here today?</label><textarea id="chief-complaint" autoFocus rows="6" maxLength="1000" value={complaint} onChange={(event) => setComplaint(event.target.value)} placeholder="For example: I have had a headache and tiredness for the past few days."/><small>{complaint.length}/1000</small><button disabled={status === "loading"} className="button-primary w-full" type="submit">{status === "loading" ? "Preparing your intake…" : "Begin conversation"}<ArrowRight size={18}/></button></form></div></section>;
  if (view === "complete") return <section className="completion-page"><span className="completion-icon"><CheckCircle2 size={32}/></span><span className="eyebrow">INTAKE SAVED</span><h1>Thank you for sharing.</h1><p>Your answers are saved as patient-reported information. Review them before your next care conversation.</p><div className="button-row"><Link className="button-primary" to={`/patient/summary?consultation=${intake?.consultationId || ""}`}>Review health summary <ArrowRight size={17}/></Link><Link className="button-secondary" to="/patient/dashboard">Back to overview</Link></div></section>;
  return <section className="conversation-page"><div className="conversation-header"><Link to="/patient/dashboard" className="back-link"><ArrowLeft size={17}/>Save and return later</Link><div><span className="card-kicker">{system === "AYUSH" ? "AYUSH INTAKE" : "HEALTH INTAKE"}</span><b>{titleCase(question?.section)}</b></div><span className="question-count">{answers.length + 1}<small>answered</small></span></div><div className="conversation-progress"><span style={{ width: `${Math.min(86, 16 + answers.length * 12)}%` }}/></div><div className="conversation-layout"><aside className="conversation-side"><span className="side-badge"><Sparkles size={16}/>Guided intake</span><h1>One question at a time.</h1><p>Your answer helps decide what information might be useful to collect next.</p><div className="answer-tally"><b>{answers.length}</b><span>answers saved<br/>in this intake</span></div></aside><main className="question-panel"><div className="question-meta"><span>Vaidyam asks</span><button onClick={speak} className="icon-button" aria-label="Read question aloud"><Volume2 size={18}/></button></div><h2>{question?.question}</h2>{question?.required && <p className="required-note">Please answer to continue.</p>}<AnswerInput question={question} answer={answer} setAnswer={setAnswer} toggle={toggle}/><div className="voice-box"><div><span className="voice-circle"><Mic size={19}/></span><span><b>{voiceState === "listening" ? "Listening…" : voiceState === "ready" ? "Transcription ready to edit" : "Prefer to speak?"}</b><small>{voiceState === "unsupported" ? "Voice input is not supported in this browser. Please type your answer." : voiceState === "permission" ? "Microphone permission was not granted. You can type instead." : "Your transcription appears in the answer field before you send it."}</small></span></div>{voiceState === "listening" ? <button className="button-secondary button-small" onClick={() => recognition.current?.stop?.()}><Pause size={15}/>Stop</button> : <button className="button-secondary button-small" onClick={startVoice}><Mic size={15}/>Use voice</button>}</div>{error && <p className="notice-error" role="alert"><CircleAlert size={18}/>{error}</p>}<div className="question-actions"><button onClick={() => setAnswer(emptyAnswer(question))} className="button-quiet"><X size={16}/>Clear</button><button disabled={status === "loading"} onClick={submit} className="button-primary">{status === "loading" ? "Saving…" : "Save answer and continue"}<Send size={17}/></button></div></main></div></section>;
}

function AnswerInput({ question, answer, setAnswer, toggle }) { if (question?.answerType === "SINGLE_SELECT") return <div className="answer-options">{(question.options || []).map((option) => <button key={option} onClick={() => setAnswer(option)} className={`answer-option ${answer === option ? "answer-option-selected" : ""}`}>{option}</button>)}</div>; if (question?.answerType === "MULTI_SELECT") return <div className="answer-options">{(question.options || []).map((option) => <button key={option} onClick={() => toggle(option)} className={`answer-option ${answer.includes(option) ? "answer-option-selected" : ""}`}>{answer.includes(option) && <CheckCircle2 size={16}/>} {option}</button>)}</div>; if (question?.answerType === "BOOLEAN") return <div className="answer-options"><button onClick={() => setAnswer(true)} className={`answer-option ${answer === true ? "answer-option-selected" : ""}`}>Yes</button><button onClick={() => setAnswer(false)} className={`answer-option ${answer === false ? "answer-option-selected" : ""}`}>No</button></div>; if (question?.answerType === "NUMBER") return <input className="answer-text-input number-input" type="number" value={answer} onChange={(event) => setAnswer(event.target.value)} placeholder="Enter a number"/>; if (question?.answerType === "DATE") return <input className="answer-text-input" type="date" value={answer} onChange={(event) => setAnswer(event.target.value)}/>; return <textarea className="answer-text-input" rows="5" value={answer} onChange={(event) => setAnswer(event.target.value)} placeholder="Type your answer here…"/>; }
